/** Demo content for `npm run seed` — idempotent by slug. */

export function lexicalFromText(text) {
  return {
    root: {
      type: 'root',
      format: '',
      indent: 0,
      version: 1,
      direction: 'ltr',
      children: [
        {
          type: 'paragraph',
          format: '',
          indent: 0,
          version: 1,
          direction: 'ltr',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text,
              version: 1,
            },
          ],
        },
      ],
    },
  }
}

export const categories = [
  { name: 'Home Services', slug: 'home-services', description: 'Residential and neighbourhood service businesses.' },
  { name: 'Food & Beverage', slug: 'food-beverage', description: 'Cafés, specialty food, and mobile food concepts.' },
  { name: 'Retail', slug: 'retail', description: 'Product-led neighbourhood retail concepts.' },
  { name: 'Wellness', slug: 'wellness', description: 'Health, fitness, and personal care businesses.' },
]

export const locations = [
  { name: 'Victoria, BC', slug: 'victoria-bc', province: 'BC', regionType: 'urban', introCopy: 'Greater Victoria and the Saanich Peninsula.' },
  { name: 'Vancouver, BC', slug: 'vancouver-bc', province: 'BC', regionType: 'urban', introCopy: 'Metro Vancouver trade areas.' },
  { name: 'Kelowna, BC', slug: 'kelowna-bc', province: 'BC', regionType: 'small-city', introCopy: 'Central Okanagan and surrounding communities.' },
]

export const consultingPackages = [
  {
    name: 'Basic Planning',
    slug: 'basic',
    tier: '1',
    tagline: 'Clarity on what to decide next',
    shortDescription: 'A focused planning sprint for founders who need direction before committing capital.',
    bestFor: [{ item: 'First-time founders validating an idea' }, { item: 'Side-project operators testing fit' }],
    deliverables: [
      { item: '90-minute planning workshop' },
      { item: 'Decision brief (PDF)' },
      { item: 'Next-step roadmap' },
    ],
    notIncluded: [{ item: 'Full financial model build' }, { item: 'Ongoing advisory' }],
    priceLabel: 'Starting at $1,200',
    turnaround: '7–10 business days',
    ctaLabel: 'Book a planning call',
  },
  {
    name: 'Accelerator',
    slug: 'accelerator',
    tier: '2',
    tagline: 'Structured plan with market and financial framing',
    shortDescription: 'Deeper research and planning for founders ready to move from idea to launch plan.',
    bestFor: [{ item: 'Founders comparing 2–3 concepts' }, { item: 'Operators planning a first location' }],
    deliverables: [
      { item: 'Market snapshot' },
      { item: 'Startup cost range model' },
      { item: 'Launch timeline' },
      { item: 'Risk and assumptions memo' },
    ],
    notIncluded: [{ item: 'Legal entity setup' }, { item: 'Lease negotiation' }],
    priceLabel: 'Starting at $3,500',
    turnaround: '2–3 weeks',
    ctaLabel: 'Book a planning call',
  },
  {
    name: 'Digital Incubator',
    slug: 'digital-incubator',
    tier: '3',
    tagline: 'Plan + digital presence foundations',
    shortDescription: 'Planning package with brand, web, and launch checklist for digital-first or hybrid businesses.',
    bestFor: [{ item: 'E-commerce or service businesses going online first' }],
    deliverables: [
      { item: 'Brand positioning one-pager' },
      { item: 'Website scope and wireframe brief' },
      { item: 'Go-to-market checklist' },
    ],
    notIncluded: [{ item: 'Full website build (quoted separately)' }],
    priceLabel: 'Contact for pricing',
    turnaround: '3–4 weeks',
    ctaLabel: 'Book a planning call',
  },
  {
    name: 'Superscaler',
    slug: 'superscaler',
    tier: '4',
    tagline: 'Multi-location or complex launch support',
    shortDescription: 'Advisory for experienced operators expanding territories or launching multiple units.',
    bestFor: [{ item: 'Multi-unit operators' }, { item: 'Franchise-style rollouts' }],
    deliverables: [
      { item: 'Territory prioritization' },
      { item: 'Unit economics template' },
      { item: '90-day execution cadence' },
    ],
    notIncluded: [{ item: 'Capital raising' }],
    priceLabel: 'Contact for pricing',
    turnaround: 'Scoped per engagement',
    ctaLabel: 'Book a planning call',
  },
]

export const concepts = [
  {
    name: 'Porchlight Pet Pantry',
    slug: 'porchlight-pet-pantry',
    placeholderBrand: 'Porchlight Pet Co.',
    categorySlug: 'retail',
    businessType: 'Neighbourhood premium pet food and essentials shop',
    shortDescription: 'Small-format pet pantry with subscription refills and local delivery in walkable neighbourhoods.',
    startupCostMin: 85000,
    startupCostMax: 140000,
    estimatedMonthlyRevenueMin: 28000,
    estimatedMonthlyRevenueMax: 52000,
    launchTimeline: '10–16 weeks',
    difficultyLevel: 'medium',
    territoryStatus: 'available',
    featured: true,
  },
  {
    name: 'Harbour Mobile Espresso',
    slug: 'harbour-mobile-espresso',
    placeholderBrand: 'Harbour Cup',
    categorySlug: 'food-beverage',
    businessType: 'Mobile specialty coffee cart with event and corporate contracts',
    shortDescription: 'Low-footprint coffee cart focused on office parks, markets, and weekend events.',
    startupCostMin: 45000,
    startupCostMax: 75000,
    estimatedMonthlyRevenueMin: 12000,
    estimatedMonthlyRevenueMax: 28000,
    launchTimeline: '6–10 weeks',
    difficultyLevel: 'low',
    territoryStatus: 'available',
    featured: true,
  },
  {
    name: 'Greenline Lawn Care',
    slug: 'greenline-lawn-care',
    placeholderBrand: 'Greenline',
    categorySlug: 'home-services',
    businessType: 'Subscription lawn care and seasonal yard tidy for suburban homes',
    shortDescription: 'Recurring residential lawn maintenance with upsells for aeration and fall cleanup.',
    startupCostMin: 25000,
    startupCostMax: 55000,
    estimatedMonthlyRevenueMin: 15000,
    estimatedMonthlyRevenueMax: 35000,
    launchTimeline: '4–8 weeks',
    difficultyLevel: 'low',
    territoryStatus: 'limited',
    featured: true,
  },
  {
    name: 'Studio North Pilates',
    slug: 'studio-north-pilates',
    placeholderBrand: 'Studio North',
    categorySlug: 'wellness',
    businessType: 'Boutique reformer pilates studio with small class sizes',
    shortDescription: '12–16 reformer capacity studio targeting professionals and active retirees.',
    startupCostMin: 180000,
    startupCostMax: 320000,
    estimatedMonthlyRevenueMin: 35000,
    estimatedMonthlyRevenueMax: 65000,
    launchTimeline: '16–24 weeks',
    difficultyLevel: 'high',
    territoryStatus: 'available',
    featured: false,
  },
  {
    name: 'Oak & Anvil Workshop',
    slug: 'oak-anvil-workshop',
    placeholderBrand: 'Oak & Anvil',
    categorySlug: 'retail',
    businessType: 'Weekend maker market and custom small-goods retail',
    shortDescription: 'Hybrid retail workshop selling curated local makers plus custom engraving services.',
    startupCostMin: 60000,
    startupCostMax: 110000,
    estimatedMonthlyRevenueMin: 18000,
    estimatedMonthlyRevenueMax: 40000,
    launchTimeline: '8–14 weeks',
    difficultyLevel: 'medium',
    territoryStatus: 'available',
    featured: true,
  },
  {
    name: 'Rise & Knead Bakery Counter',
    slug: 'rise-knead-bakery',
    placeholderBrand: 'Rise & Knead',
    categorySlug: 'food-beverage',
    businessType: 'Artisan bakery counter with coffee and wholesale mornings',
    shortDescription: 'Morning-focused bakery with wholesale bread runs to cafés and grocers.',
    startupCostMin: 120000,
    startupCostMax: 220000,
    estimatedMonthlyRevenueMin: 32000,
    estimatedMonthlyRevenueMax: 58000,
    launchTimeline: '14–20 weeks',
    difficultyLevel: 'high',
    territoryStatus: 'limited',
    featured: false,
  },
  {
    name: 'Clearview Home Organizing',
    slug: 'clearview-home-organizing',
    placeholderBrand: 'Clearview',
    categorySlug: 'home-services',
    businessType: 'Home organizing and move-in reset services',
    shortDescription: 'Premium organizing for downsizers, relocations, and home office setups.',
    startupCostMin: 8000,
    startupCostMax: 25000,
    estimatedMonthlyRevenueMin: 8000,
    estimatedMonthlyRevenueMax: 22000,
    launchTimeline: '2–4 weeks',
    difficultyLevel: 'low',
    territoryStatus: 'available',
    featured: false,
  },
  {
    name: 'Tidepool Kids Activity Lounge',
    slug: 'tidepool-kids-lounge',
    placeholderBrand: 'Tidepool',
    categorySlug: 'wellness',
    businessType: 'Indoor play lounge with classes and birthday parties',
    shortDescription: 'Membership-based kids activity space with party packages and café partnership.',
    startupCostMin: 150000,
    startupCostMax: 280000,
    estimatedMonthlyRevenueMin: 40000,
    estimatedMonthlyRevenueMax: 75000,
    launchTimeline: '20–28 weeks',
    difficultyLevel: 'high',
    territoryStatus: 'sold',
    featured: false,
  },
  {
    name: 'Copper Kettle Meal Prep',
    slug: 'copper-kettle-meal-prep',
    placeholderBrand: 'Copper Kettle',
    categorySlug: 'food-beverage',
    businessType: 'Weekly meal prep subscription kitchen',
    shortDescription: 'Delivery-first meal prep with pickup hubs in suburban neighbourhoods.',
    startupCostMin: 70000,
    startupCostMax: 130000,
    estimatedMonthlyRevenueMin: 25000,
    estimatedMonthlyRevenueMax: 48000,
    launchTimeline: '10–14 weeks',
    difficultyLevel: 'medium',
    territoryStatus: 'available',
    featured: true,
  },
  {
    name: 'Summit Bike Tune & Trail',
    slug: 'summit-bike-tune',
    placeholderBrand: 'Summit Cycle',
    categorySlug: 'retail',
    businessType: 'Bike service shop with trail-side pop-up tune-ups',
    shortDescription: 'Seasonal bike service with mobile tune-up stops at popular trailheads.',
    startupCostMin: 55000,
    startupCostMax: 95000,
    estimatedMonthlyRevenueMin: 20000,
    estimatedMonthlyRevenueMax: 42000,
    launchTimeline: '8–12 weeks',
    difficultyLevel: 'medium',
    territoryStatus: 'available',
    featured: false,
  },
]

export const resources = [
  {
    title: 'How to choose your first business concept',
    slug: 'choose-first-business-concept',
    category: 'planning',
    excerpt: 'A practical framework for comparing ideas without falling in love with the wrong one.',
    readingTime: 8,
  },
  {
    title: 'Startup cost ranges: what the numbers actually include',
    slug: 'startup-cost-ranges-explained',
    category: 'financials',
    excerpt: 'Equipment, leaseholds, working capital, and the line items founders forget.',
    readingTime: 10,
  },
  {
    title: 'Picking a trade area in BC',
    slug: 'picking-trade-area-bc',
    category: 'location',
    excerpt: 'How to read demographics, competition, and drive patterns before you sign a lease.',
    readingTime: 12,
  },
  {
    title: 'Launch timeline checklist',
    slug: 'launch-timeline-checklist',
    category: 'planning',
    excerpt: 'A week-by-week checklist from decision to opening day for a typical small-format business.',
    readingTime: 6,
  },
  {
    title: 'Grants and founder programs in Western Canada',
    slug: 'grants-western-canada',
    category: 'funding',
    excerpt: 'Where to look for non-dilutive support, and what you need before you apply.',
    readingTime: 9,
  },
  {
    title: 'When a business concept is not for you',
    slug: 'concept-fit-honest-guide',
    category: 'concepts',
    excerpt: 'Operator fit matters. Here is how we think about skills, capital, and lifestyle match.',
    readingTime: 7,
  },
]
